# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GeneratingAndManagingTestDataSampleApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GeneratingAndManagingTestDataSampleApp

  target 'GeneratingAndManagingTestDataSampleAppUITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Fakery'
  end

end
